image: rduweston/ubuntu-ci:18.04

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script:
  #   - sudo apt update && apt -y install wget
  script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . && cpack
#   artifacts:
#     paths:
#       - mybinary
      # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
      # cache:
      #   paths:
      #     - "*.o"

# run tests using the binary built before
# test:
#   stage: test
#   script:
#     - ./runmytests.sh
