## Build and test as standard C++ package
cpp-build:
  stage: cpp-build
  image: rduweston/ubuntu-ci:18.04
  before_script:
    - apt update && apt -y install libasio-dev
  script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . && cpack
  # artifacts:
  #   paths:
  #     - build/bin
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

cpp-test:
  stage: cpp-test
  image: rduweston/ubuntu-ci:18.04
  before_script:
    - apt update && apt -y install libasio-dev
  script:
    - mkdir build && cd build
    - cmake -DBUILD_TESTS=ON ..
    - cmake --build .
    - ./build/bin/gtest_all
  # dependencies:
  #   - cpp-build
