## Build and test as standard C++ package
cpp-build:
  stage: build
  image: rduweston/ubuntu-ci:18.04
  before_script:
    - apt update && apt -y install libasio-dev
  script:
    - mkdir build && cd build
    - cmake ..
    - cmake --build . && cpack
  # artifacts:
  #   paths:
  #     - build/bin
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

cpp-test:
  stage: test
  image: rduweston/ubuntu-ci:18.04
  before_script:
    - apt update && apt -y install libasio-dev
  script:
    - mkdir build && cd build
    - cmake -DBUILD_TESTS=ON ..
    - cmake --build .
    - ./bin/gtest_all
  # dependencies:
  #   - cpp-build

## Build and test as catkin package
catkin-build:
  stage: build
  image: rduweston/ubuntu-ci:melodic-bionic
  before_script:
    - apt update && apt -y install libasio-dev
  script:
    - cd $CI_PROJECT_PATH && pwd
    - mkdir -p /catkin_ws/src && cd /catkin_ws/src && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_init_workspace"
    - cd /catkin_ws/src && cp -r $CI_PROJECT_PATH .
    - cd /catkin_ws && /bin/bash -c "source /opt/ros/${ROS_DISTRO}/setup.bash; catkin_make"